version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deeplant-admin
    overwrite: yes

permissions:
  - object: /home/ubuntu/deeplant-admin

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_flask.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      runas: ubuntu
