version: '3.8'

services:
  admin-server:
    build:
      context: ./test-flask
      dockerfile: Dockerfile
    container_name: admin-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./test-flask/.env
      - ./test-flask/serviceAccountKey.json

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-grafana/prometheus/config:/etc/prometheus
      - ./prometheus-grafana/prometheus/volume:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./prometheus-grafana/grafana/volume:/var/lib/grafana
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "9100:9100"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.0
    container_name: mlflow
    ports:
      - "5000:5000"
    restart: unless-stopped
