name: Backend CI

on:
  push:
    branches:
      - feature/back
    paths:
      - test-backend/test-flask/**
  pull_request:
    branches:
      - feature/back
    paths:
      - test-backend/test-flask/**

env:
  DB_URI: ${{secrets.DB_URI}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
  S3_REGION_NAME: ${{secrets.S3_REGION_NAME}}
  FIREBASE_BUCKET_ADDRESS: ${{secrets.FIREBASE_BUCKET_ADDRESS}}

jobs:
  test-on-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Set environment variables
        run: |
          cd test-backend/test-flask
          echo "DB_URI=$DB_URI" >> .env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env
          echo "S3_REGION_NAME=$S3_REGION_NAME" >> .env
          echo "FIREBASE_BUCKET_ADDRESS=$FIREBASE_BUCKET_ADDRESS" >> .env
          cd ../../

      - name: Set serviceAccountKey JSON
        env:
          serviceAccountKey: ${{secrets.SERVICEACCOUNTKEY}}
        run: |
          cd test-backend/test-flask
          echo "$serviceAccountKey" > serviceAccountKey.json
          cd ../../

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r test-backend/test-flask/requirements.txt

      # - name: Run tests
      #  run: |
      #    source venv/bin/activate
      #    pytest test-backend/test-flask/tests

  test-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: feature/back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Set environment variables
        run: |
          cd test-backend/test-flask
          echo "DB_URI=$DB_URI" >> .env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env
          echo "S3_REGION_NAME=$S3_REGION_NAME" >> .env
          echo "FIREBASE_BUCKET_ADDRESS=$FIREBASE_BUCKET_ADDRESS" >> .env
          cd ../../

      - name: Set serviceAccountKey JSON
        env:
          serviceAccountKey: ${{secrets.SERVICEACCOUNTKEY}}
        run: |
          cd test-backend/test-flask
          echo "$serviceAccountKey" > serviceAccountKey.json
          cd ../../

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r test-backend/test-flask/requirements.txt

    #   - name: Run tests
    #     run: |
    #       source venv/bin/activate
    #       pytest test-backend/test-flask/tests
    #       continue-on-error: false
